### ISSUE TITLE
关于命令面板快捷键打不开的询问

### ISSUE THREAD

**Issue by real-jiakai** [youhuangla/Note#1]
大哥，你好。看了你的b站链接。我目前有一个问题。我按住了键盘上的?键但是并没有将这个快捷命令帮助面板呈现出来，反而是跳转到github的搜索框。官方文档也是问号键，打开快捷命令面板。请问你是按住问号键打开下图的嘛？
![image](https://user-images.githubusercontent.com/82650452/166838942-bec7e6b1-bf09-4ddb-99b9-d2e42e2245aa.png)
![image](https://user-images.githubusercontent.com/82650452/166839451-20b76b11-00bb-46ed-8c2e-f328a4d1a0db.png)
网上没搜到对应的解答。期待你的回复。

**Comment by youhuangla** [comment]
试试Shift+/键，也就是你怎么打英文的"?"的。Keyboard shortcuts在当前的页面就可以打开

**Comment by Jaya0455** [comment]
是的，shift+/解决了我的问题。感谢你的解答。👍👍👍
